const HELPERS = {
  countries: [
    { id: "ae", value: "United Arab Emirates" },
    { id: "ar", value: "Argentina" },
    { id: "at", value: "Austria" },
    { id: "au", value: "Australia" },
    { id: "be", value: "Belgium" },
    { id: "bg", value: "Bulgaria" },
    { id: "br", value: "Brazil" },
    { id: "ca", value: "Canada" },
    { id: "ch", value: "Switzerland" },
    { id: "cn", value: "China" },
    { id: "co", value: "Colombia" },
    { id: "cu", value: "Cuba" },
    { id: "cz", value: "Czech Republic" },
    { id: "de", value: "Germany" },
    { id: "eg", value: "Egypt" },
    { id: "fr", value: "France" },
    { id: "gb", value: "United Kingdom" },
    { id: "gr", value: "Greece" },
    { id: "hk", value: "Hong Kong" },
    { id: "hu", value: "Hungary" },
    { id: "id", value: "Indonesia" },
    { id: "ie", value: "Ireland" },
    { id: "il", value: "Israel" },
    { id: "in", value: "India" },
    { id: "it", value: "Italy" },
    { id: "jp", value: "Japan" },
    { id: "kr", value: "South Korea" },
    { id: "lt", value: "Lithuania" },
    { id: "lv", value: "Latvia" },
    { id: "ma", value: "Morocco" },
    { id: "mx", value: "Mexico" },
    { id: "my", value: "Malaysia" },
    { id: "ng", value: "Nigeria" },
    { id: "nl", value: "Netherlands" },
    { id: "no", value: "Norway" },
    { id: "nz", value: "New Zealand" },
    { id: "ph", value: "Philippines" },
    { id: "pl", value: "Poland" },
    { id: "pt", value: "Portugal" },
    { id: "ro", value: "Romania" },
    { id: "rs", value: "Serbia" },
    { id: "ru", value: "Russia" },
    { id: "sa", value: "Saudi Arabia" },
    { id: "se", value: "Sweden" },
    { id: "sg", value: "Singapore" },
    { id: "si", value: "Slovenia" },
    { id: "sk", value: "Slovakia" },
    { id: "th", value: "Thailand" },
    { id: "tr", value: "Turkey" },
    { id: "tw", value: "Taiwan" },
    { id: "ua", value: "Ukraine" },
    { id: "us", value: "United States" },
    { id: "ve", value: "Venezuela" },
    { id: "za", value: "South Africa" },
  ],
  categories: [
    { id: "business", value: "Business" },
    { id: "entertainment", value: "Entertainment" },
    { id: "general", value: "General" },
    { id: "health", value: "Health" },
    { id: "science", value: "Science" },
    { id: "sports", value: "Sports" },
    { id: "technology", value: "Technology" },
  ],
  links: [
    { route: "", name: "Inicio" },
    { route: "", name: "Categorias" },
    { route: "", name: "Autores" },
  ],
};
export default HELPERS;
